In [2]:
import torch

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.datasets import fetch_california_housing

# California Housing veri setini yükleme
housing = fetch_california_housing()

In [3]:
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [8]:
from sklearn.datasets import fetch_california_housing
import torch

# California Housing veri setini yükleme
housing = fetch_california_housing()

# Özellikler ve hedef değişkenini al
X = housing.data  # Bu, NumPy dizisi zaten
y = housing.target  # Hedef değişken

# PyTorch tensor'lerine dönüştürme
X_tensor = torch.from_numpy(X).float()  # X verisini tensor'e dönüştürme
y_tensor = torch.from_numpy(y).float()  # Hedef verisini tensor'e dönüştürme

print(X_tensor)
print(y_tensor)


tensor([[   8.3252,   41.0000,    6.9841,  ...,    2.5556,   37.8800,
         -122.2300],
        [   8.3014,   21.0000,    6.2381,  ...,    2.1098,   37.8600,
         -122.2200],
        [   7.2574,   52.0000,    8.2881,  ...,    2.8023,   37.8500,
         -122.2400],
        ...,
        [   1.7000,   17.0000,    5.2055,  ...,    2.3256,   39.4300,
         -121.2200],
        [   1.8672,   18.0000,    5.3295,  ...,    2.1232,   39.4300,
         -121.3200],
        [   2.3886,   16.0000,    5.2547,  ...,    2.6170,   39.3700,
         -121.2400]])
tensor([4.5260, 3.5850, 3.5210,  ..., 0.9230, 0.8470, 0.8940])


In [9]:
X_tensor.size()

torch.Size([20640, 8])

In [10]:
y_tensor.size()

torch.Size([20640])

In [14]:
from PIL import Image
import numpy as np

In [16]:
kedy=np.array(Image.open("kedi1.jpg").resize((224,224)))
kedy

array([[[136, 133, 126],
        [137, 134, 127],
        [138, 135, 128],
        ...,
        [145, 142, 137],
        [145, 142, 137],
        [143, 140, 135]],

       [[136, 133, 126],
        [138, 135, 128],
        [138, 135, 128],
        ...,
        [145, 142, 137],
        [145, 142, 137],
        [143, 140, 135]],

       [[137, 134, 127],
        [137, 134, 127],
        [137, 134, 127],
        ...,
        [145, 142, 137],
        [145, 142, 137],
        [144, 141, 136]],

       ...,

       [[188, 189, 184],
        [185, 186, 181],
        [190, 191, 186],
        ...,
        [141, 136, 130],
        [139, 134, 128],
        [139, 134, 128]],

       [[179, 180, 175],
        [179, 180, 175],
        [183, 184, 179],
        ...,
        [125, 120, 114],
        [120, 115, 109],
        [120, 115, 109]],

       [[169, 170, 165],
        [173, 174, 169],
        [175, 176, 171],
        ...,
        [116, 111, 105],
        [109, 104,  98],
        [108, 103,  97]]

In [18]:
kedytorch=torch.from_numpy(kedy)

np.shape(kedy)

(224, 224, 3)

In [19]:
kedytorch.size()

torch.Size([224, 224, 3])

In [23]:
import matplotlib.pyplot as plt

In [25]:
plt.imsave("kedi",kedytorch)

TypeError: Cannot interpret 'torch.uint8' as a data type