In [1]:
import torch
import torch.nn as nn
from sklearn.datasets import load_breast_cancer

In [2]:
device=torch.device("cpu")

In [13]:
input_size=30
hidden_size=500
num_classes=2 #iyi huylu tümor veya kötü huylu tümör 
learning_rate=1e-5 #modelin öğrenme sıklığı 10 üzeri -8  .çok sık ogrenemedi bunu arttırcam
num_epoch = 150 #100 adımı vardı 150 .ektim daha fazla öğrensin  ve  yukarıdakini -8i -5b yaptım daha sık iyi öğrenbsin
girdi,cikti=load_breast_cancer(return_X_y=True)

print(girdi)
print(girdi.shape)
print(cikti)
print(cikti.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
(569, 30)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 

In [14]:
train_input=torch.from_numpy(girdi).float()
train_output=torch.from_numpy(cikti).long()

class NeuralNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNetwork,self).__init__()
        self.fc1=nn.Linear(input_size,hidden_size)
        self.lrelu=nn.LeakyReLU(negative_slope=0.02)
        self.fc2=nn.Linear(hidden_size,num_classes)
        
    def forward(self,input):
        outfc1=self.fc1(input)
        outfc1relu=self.lrelu(outfc1)
        out=self.fc2(outfc1relu)
        return out
    
model=NeuralNetwork(input_size,hidden_size,num_classes)



lossf=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

for epoch in range(num_epoch):
    
        outputs=model(train_input)
        loss=lossf(outputs,train_output)
        
        optimizer.zero_grad()
        loss.backward()
        
        optimizer.step() #optimizasyon tanıumlanır    her seferinde opt. sıfırla ağırlık gradyan güncelle  sonra opt. tanımla
        #eğer sıfırlanamzsam türevleri sürekli üzerine ekleyerek gider
        
    
        print("Epoch : {}-{}  Lossf {:.4f}".format(epoch+1,num_epoch,loss.item()))

Epoch : 1-150  Lossf 25.7023
Epoch : 2-150  Lossf 25.3471
Epoch : 3-150  Lossf 24.9919
Epoch : 4-150  Lossf 24.6367
Epoch : 5-150  Lossf 24.2815
Epoch : 6-150  Lossf 23.9263
Epoch : 7-150  Lossf 23.5711
Epoch : 8-150  Lossf 23.2159
Epoch : 9-150  Lossf 22.8607
Epoch : 10-150  Lossf 22.5056
Epoch : 11-150  Lossf 22.1504
Epoch : 12-150  Lossf 21.7952
Epoch : 13-150  Lossf 21.4400
Epoch : 14-150  Lossf 21.0848
Epoch : 15-150  Lossf 20.7296
Epoch : 16-150  Lossf 20.3744
Epoch : 17-150  Lossf 20.0192
Epoch : 18-150  Lossf 19.6640
Epoch : 19-150  Lossf 19.3088
Epoch : 20-150  Lossf 18.9537
Epoch : 21-150  Lossf 18.5985
Epoch : 22-150  Lossf 18.2433
Epoch : 23-150  Lossf 17.8881
Epoch : 24-150  Lossf 17.5330
Epoch : 25-150  Lossf 17.1778
Epoch : 26-150  Lossf 16.8227
Epoch : 27-150  Lossf 16.4676
Epoch : 28-150  Lossf 16.1124
Epoch : 29-150  Lossf 15.7573
Epoch : 30-150  Lossf 15.4022
Epoch : 31-150  Lossf 15.0471
Epoch : 32-150  Lossf 14.6920
Epoch : 33-150  Lossf 14.3369
Epoch : 34-150  Los

In [ ]:
#sınıf sayısı 1 ve dah fazlaysa cross ent. kullanabiliriz  toplamları 1 olacak şekilde her sınıfı yüzde üzerinden o girdinin
#kaç olabileceğini verir
#modelinizin tahmin ettiği olasılıklar ile gerçek sınıf etiketleri arasındaki uyumsuzluğu ölçer.minimize etmek.

#softmmax Softmax, bir dizi sayıyı (genellikle logits adı verilen ham skorları), her bir elemanın toplamda 1 olacak şekilde 
#bir olasılık  dağılımına dönüştüren matematiksel bir fonksiyondur. Özellikle sınıflandırma problemlerinde, modelin her bir sınıf 
#için tahmin ettiği olasılıkları hesaplamak için kullanılır.

In [ ]:
#ÖNEMLİ Aktivasyon fonksiyonlarıdır 
Softmax, Sigmoid ve diğer aktivasyon fonksiyonları, derin öğrenme modellerinde tahmin yapmayı kolaylaştıran matematiksel
araçlardır. Her bir fonksiyonun temel amacı, modelin çıktısını işleyerek belirli bir forma (örneğin olasılık dağılımı) 
dönüştürmek ve daha iyi bir öğrenme süreci sağlamaktır. Şimdi bu fonksiyonları ve aralarındaki farkları detaylıca inceleyelim.

1. Aktivasyon Fonksiyonlarının Genel Rolü
Aktivasyon fonksiyonları, yapay sinir ağlarında her bir nöronun çıktısını belirlemek için kullanılır. Özellikle:

Doğrusal olmayanlık ekleyerek modeli daha güçlü hale getirir.
Modelin belirli bir problem (sınıflandırma, regresyon vb.) için çıktısını uygun bir şekilde dönüştürür.
Tahmin sonucunu normalize ederek anlamlı hale getirir (örneğin, olasılık).

In [ ]:
3. Sigmoid Fonksiyonu
Sigmoid, bir sayıyı 
0
0 ile 
1
1 arasında bir değere dönüştüren fonksiyondur.

Kullanım Alanı:
İkili sınıflandırma problemlerinde (örneğin, hastalık var mı yok mu).
Çok etiketli sınıflandırma (multi-label classification), çünkü her sınıf birbirinden bağımsız değerlendirilir.
Örnek:
Bir modelin çıktısı: 
2.0
2.0.
Sigmoid sonrası: 
0.88
0.88.
Bu, girdinin %88 ihtimalle pozitif sınıfa ait olduğunu gösterir.



In [ ]:
ReLU, doğrusal olmayan bir fonksiyondur ve negatif değerleri sıfıra çeker, pozitif değerleri olduğu gibi bırakır.
Kullanım Alanı:
Gizli katmanlarda, özellikle derin öğrenme modellerinde öğrenmeyi hızlandırmak için.
Negatif çıktıları sıfırlayarak sparsity (seyreklik) sağlar.

In [ ]:
Softmax, genellikle sınıflandırma problemlerinde son katman olarak kullanılır. Örneğin, bir model bir görüntünün 3 farklı 
sınıfa (kedi, köpek, kuş) ait olma olasılıklarını tahmin edebilir.

Örnek:

python
Kodu kopyala
import torch
import torch.nn.functional as F

# Logits (modelin çıktısı)
logits = torch.tensor([2.0, 1.0, 0.1])

# Softmax fonksiyonu
probabilities = F.softmax(logits, dim=0)

print(probabilities)  # Sınıf olasılıkları toplamı 1 olacak
Çıktı örneği:

scss
Kodu kopyala
tensor([0.6590, 0.2424, 0.0986])
Bu, girişin %65.9 ihtimalle birinci sınıfa, %24.2 ihtimalle ikinci sınıfa, %9.86 ihtimalle üçüncü sınıfa ait olduğunu gösterir.

Softmax vs. Sigmoid:
Softmax: Birden fazla sınıf arasında seçim yapmak için kullanılır. Sınıflar birbirini dışlar (mutually exclusive).
Sigmoid: Her sınıfın birbirinden bağımsız olduğu durumlarda (örneğin, çok etiketli sınıflandırma) kullanılır.
Avantajları:
Birden fazla sınıfa ait olasılık tahminleri yapmayı sağlar.
Modelin çıktısını daha kolay yorumlamaya olanak tanır.
Özet:
Softmax, sınıflandırma problemlerinde modelin her bir sınıf için tahmin ettiği olasılıkları hesaplamakta kullanılan bir fonksiyondur
. Modelin tahminlerinin toplamının 1 olmasını sağlar, bu da olasılık dağılımı üretmeyi kolaylaştırır.

In [ ]:
Aktivasyon fonksiyonları doğrudan tahmin yapmaz, ancak modelin tahminlerini anlamlı hale getirir:  yani biz anlayalım diye
    saçma sağan değer yazdırmak yerine %60 doğruluk oranı olduğunu yazdıırıyoor

Softmax, sınıfların olasılıklarını üretir. Tahmin edilen sınıf, en yüksek olasılığı olan sınıftır.
Sigmoid, pozitif sınıfa ait olma olasılığını verir.
ReLU ve Tanh, daha çok ara katmanlarda kullanılır; tahmin sonuçlarıyla doğrudan bağlantılı değildir.
Özet
Softmax: Çok sınıflı sınıflandırmada, sınıf olasılıklarını oluşturur.
Sigmoid: İkili sınıflandırmada veya bağımsız çok etiketli problemler için kullanılır.
ReLU ve Tanh: Daha çok öğrenme sürecini hızlandırmak ve doğrusal olmayanlık eklemek için gizli katmanlarda kullanılır.
Bu fonksiyonlar, modelin çıktısını işleyerek öğrenmeyi ve tahmini daha etkili hale getirir. Doğru fonksiyon seçimi, problem türüne bağlıdır.

In [ ]:
#optimizerlardır bi nevi bu backprobagationda olan kayıp fonk. da gelen hata oranını minilize etmek ağırlıkları güncelleme 
#işlemlerinin arkaplanda asıl yapanlardan biridir 

Evet, optimizer, backpropagation sırasında hesaplanan gradyanları (gradient) kullanarak model parametrelerini güncellemekten
sorumludur. Ancak tek başına tüm işlemleri yapan bir bileşen değildir.
İşlem zincirinin bir parçasıdır. Bu zinciri adım adım açıklayalım:

Forward Pass
Ne olur?

Model, giriş verileri üzerinden bir tahmin (prediction) yapar.   ilk verilerden tahmin yaptı öylesine (ama uygun tahmin)ve ileriye dönük 
Bu tahmin, ileri yönlü bir hesaplama (forward pass) sonucunda oluşur.
Aktif Eleman: Modelin katmanları ve aktivasyon fonksiyonlarıdır.
Örneğin, model(inputs) çağrıldığında, bu işlem gerçekleşir.

Loss Function
Ne olur?
Modelin tahminleri (preds) ve gerçek hedefler (targets) arasındaki fark hesaplanır.
Bu fark, bir kayıp fonksiyonu (loss function) tarafından bir ölçüye dönüştürülür.
Örneğin, MSE, CrossEntropyLoss, BinaryCrossEntropy.
Aktif Eleman: Loss function.
    
Backward Pass (Backpropagation)
Ne olur?
Kayıp fonksiyonu, model parametrelerine (ağırlıklar ve biaslar) göre türevlenir (gradyanlar hesaplanır).
Bu işlem, otomatik türevleme (autograd) mekanizması tarafından gerçekleştirilir.
Aktif Elemanlar: PyTorch gibi framework'lerin loss.backward() metodu.
Bu aşamada, gradyanlar w.grad ve b.grad gibi değişkenlerde saklanır.

Optimizer
Ne yapar?
Backpropagation'ın ürettiği gradyanları kullanarak model parametrelerini günceller.
Gradyanlar, optimizer'ın algoritmasına (SGD, Adam, RMSprop vb.) bağlı olarak işlenir.
Formül:
𝜃
=
𝜃
−
𝜂
⋅
∇
𝐽
(
𝜃
)
θ=θ−η⋅∇J(θ)
𝜃
θ: Model parametreleri (örneğin ağırlıklar, biaslar).
𝜂
η: Öğrenme oranı.
∇
𝐽
(
𝜃
)
∇J(θ): Kayıp fonksiyonunun gradyanı.
Aktif Elemanlar: opt.step().
Optimizer'ın Rolü
Backpropagation Sonrası Gelen İşlem:
Backpropagation, sadece gradyanları hesaplar. Modelin parametrelerini değiştirmez.
Optimizasyon işlemi, bu gradyanları kullanarak parametreleri günceller.
Kaybı Minimize Etmek:
Gradyanlar, kayıp fonksiyonunun eğimini temsil eder. Optimizer, bu eğimi takip ederek kaybı minimize eder.
Model bu şekilde daha doğru tahminler yapmayı öğrenir.
Forward, Loss, Backward ve Optimizer İlişkisi
Bu işlemleri bir araya getirirsek:

Forward Pass:
Model tahmin yapar. preds = model(inputs)
Loss Hesaplama:
Kayıp hesaplanır. loss = loss_fn(preds, targets)
Backward Pass:
Gradyanlar hesaplanır. loss.backward()
Optimizer:
Parametreler güncellenir. opt.step()
Gradyanlar sıfırlanır. opt.zero_grad()
Sonuç
Optimizer, backpropagation'dan sonra gradyanları kullanarak parametreleri güncelleyen bileşendir.
Ancak tahmin işlemini yapan forward pass, kaybı hesaplayan loss function, ve gradyanları hesaplayan backpropagation birbirin
den bağımsız çalışır ama birbiriyle ilişkilidir. Optimizasyon işlemi, tüm bu adımları bir araya getirerek modeli eğitir.

