In [5]:
from torch.nn import Linear
import numpy as np
import torch

In [ ]:
meslea DL de katmanlar oluştururken katmanlar için yazılacak algoritmaları tek tek alt alta sıralya add ile ekliyoruz işte
model.add(Conv2D) 1. katman 
model.add(Conv) 2. katman 
model.add(output=1,loss func= cross entopy) 3. katman 


pytorchda boyle degilde hepsini iç içe yazdırabiliyorsun
 print(lin2(lin1(inp)))
    
    yani kompleks ağlar yazılabiliyor ağ yapılar kolayca yapılabilir GAN 

In [11]:
inp=torch.rand(1)
inp

tensor([0.5746])

In [12]:
linear=Linear(in_features=1,out_features=1)
linear.weight,linear.bias

(Parameter containing:
 tensor([[0.7314]], requires_grad=True),
 Parameter containing:
 tensor([0.1551], requires_grad=True))

In [15]:
lin1=Linear(in_features=1,out_features=5)
lin2=Linear(in_features=5,out_features=2)
print(lin1(inp))

tensor([ 0.9718,  0.4486,  0.2567,  0.7241, -0.5175], grad_fn=<ViewBackward0>)


In [21]:
lin1.weight

Parameter containing:
tensor([[ 0.6494],
        [ 0.4504],
        [-0.9685],
        [ 0.0736],
        [-0.5619]], requires_grad=True)

In [22]:
lin2.weight

Parameter containing:
tensor([[-0.3260, -0.4112,  0.4280, -0.2558,  0.1302],
        [ 0.1054,  0.1516, -0.3730,  0.4148,  0.2056]], requires_grad=True)

In [14]:
 print(lin2(lin1(inp)))

tensor([-0.1402,  0.0171,  0.3535], grad_fn=<ViewBackward0>)
