In [4]:
from torch import nn

class network(nn.Module):
    def __init__(self):
        super().__init__()

        self.hidden=nn.Linear(784,256)#bura ilk parametre giriş 2.si gizli katman 
        
        
        self.output=nn.Linear(256,10)#burada ilk parametre gizli katman ikincisi çıkış 
        
        self.sigmoid=nn.Sigmoid()
        self.softmax=nn.Softmax(dim=1)
        
    def printle(self,x):
        x=self.hidden(x)
        x=self.output(x)
        x=self.sigmoid(x)
        x=self.softmax(x)
        
        
        return x

In [5]:
m=network()
m

network(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
)

In [8]:
import torch.nn.functional as F

class network(nn.Module):
    def __init__(self):
        super().__init__()

        self.hidden=nn.Linear(784,256)#bura ilk parametre giriş 2.si gizli katman 
        
        
        self.output=nn.Linear(256,10)#burada ilk parametre gizli katman ikincisi çıkış 
        
    def printl(self,x):
        x=F.sigmoid(self.hidden(x))
        
        x=F.sigmoid(self.sigmoid(x),dim=1)
        
        return x

In [9]:
m=network()
m

network(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [11]:
m.hidden.weight

Parameter containing:
tensor([[-0.0305,  0.0277, -0.0115,  ...,  0.0302,  0.0042, -0.0130],
        [-0.0110,  0.0110,  0.0014,  ...,  0.0088,  0.0016, -0.0226],
        [-0.0172, -0.0341,  0.0286,  ...,  0.0012,  0.0356,  0.0111],
        ...,
        [ 0.0182,  0.0184,  0.0353,  ..., -0.0067, -0.0146, -0.0226],
        [-0.0100,  0.0241,  0.0252,  ...,  0.0331,  0.0221,  0.0340],
        [-0.0253,  0.0064,  0.0116,  ...,  0.0276, -0.0330, -0.0128]],
       requires_grad=True)

In [12]:
m.output.bias

Parameter containing:
tensor([-0.0377, -0.0545, -0.0372, -0.0581,  0.0369, -0.0171, -0.0120,  0.0475,
        -0.0192, -0.0303], requires_grad=True)

In [14]:
m.hidden.bias.data.fill_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [15]:
m.hidden.weight.data.normal_(std=0.01)#hidden katmanındaki ağırlıkların hepsini N(0, 0.01^2) dağılımına göre rastgele değerlere ayarlayacaktır.

tensor([[-0.0122,  0.0003,  0.0123,  ..., -0.0062,  0.0019,  0.0110],
        [ 0.0025,  0.0082,  0.0144,  ...,  0.0005, -0.0073, -0.0078],
        [-0.0035,  0.0036,  0.0018,  ..., -0.0069, -0.0067, -0.0123],
        ...,
        [-0.0017, -0.0113,  0.0287,  ..., -0.0177,  0.0070,  0.0113],
        [-0.0033,  0.0095,  0.0064,  ..., -0.0044,  0.0085,  0.0211],
        [-0.0079, -0.0023,  0.0087,  ...,  0.0038, -0.0095,  0.0075]])

In [17]:
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Verileri dönüştürme işlemi
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

# MNIST veri setini yükleme
trainset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

# DataLoader oluşturma
trainloader = DataLoader(trainset, batch_size=64, shuffle=True)


Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.91M/9.91M [00:13<00:00, 711kB/s]


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 161kB/s]


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.65M/1.65M [00:01<00:00, 1.06MB/s]


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.54k/4.54k [00:00<?, ?B/s]

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw



In [21]:
import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(784, 10)  # Örneğin, 784 giriş, 10 çıkış

    def forward(self, x):
        x = self.fc(x)
        return x


In [22]:
model = SimpleModel()


In [23]:
# Örnek veri: 64 örneklik bir batch, 28x28 boyutunda
inputs = torch.randn(64, 1, 28, 28)

# Veriyi düzleştirme: (batch_size, 784)
inputs = inputs.view(64, -1)


In [24]:
outputs = model(inputs)

# Çıktıyı inceleyin
print(outputs.shape)  # Çıktı: torch.Size([64, 10])


torch.Size([64, 10])


In [ ]:
Veri Şeklinin Düzleştirilmesi
MNIST gibi veri setlerinden alınan görüntüler genellikle 2 boyutludur (28x28 piksel). Ancak bu iki boyutlu yapı, bir tam bağlı katman tarafından işlenemez. Bu nedenle:

Görüntünün her pikselini bir özellik (feature) olarak ele alırız.
28x28 = 784 pikseli bir vektör haline getiririz (flattening/düzleştirme).
Düzleştirme işlemi şunu yapar:

python
Kodu kopyala
# Önce: (64, 1, 28, 28) -> Batch size: 64, Kanal: 1, Yükseklik: 28, Genişlik: 28
inputs = inputs.view(64, -1)
# Sonra: (64, 784) -> Batch size: 64, Özellik sayısı: 784

In [ ]:
buralarda kullanlır
1. Tam Bağlı Katmanlara (Fully Connected Layers) Geçmeden Önce
Tam bağlı katmanlar (nn.Linear) giriş olarak her bir örneği bir vektör olarak bekler. Eğer modelinizde tam bağlı bir katman varsa ve giriş veriniz çok boyutluysa (örneğin, bir görüntü), tam bağlı katmanla işlenebilmesi için düzleştirme yapmanız gerekir.

Ne zaman:

Convolutional Neural Network (CNN) sonrası:
Örneğin, CNN çıkışını tam bağlı bir katmana bağlamadan önce.
python
Kodu kopyala
x = x.view(x.size(0), -1)  # Batch boyutunu koruyarak düzleştirme
Örnek:

python
Kodu kopyala
import torch
import torch.nn as nn

class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()
        self.conv = nn.Conv2d(1, 16, kernel_size=3)
        self.fc = nn.Linear(16 * 26 * 26, 10)  # CNN sonrası düzleştirilmiş giriş

    def forward(self, x):
        x = self.conv(x)  # (batch_size, 16, 26, 26)
        x = x.view(x.size(0), -1)  # Düzleştirme
        x = self.fc(x)  # (batch_size, 10)
        return x
2. Doğrudan Düzleştirilmiş Veri Kullandığınızda
Eğer veri setiniz 2D (örneğin, görüntü) veya 3D (örneğin, ses) formatındaysa, ancak modeliniz bu verileri 1D vektör olarak bekliyorsa, düzleştirme yapmanız gerekir.

Örnek:

MNIST (28x28 görüntüler):

python
Kodu kopyala
inputs = inputs.view(inputs.size(0), -1)  # (batch_size, 784)
CIFAR-10 (3 kanallı 32x32 görüntüler):

python
Kodu kopyala
inputs = inputs.view(inputs.size(0), -1)  # (batch_size, 3072)
3. Convolutional Neural Network (CNN) Olmadığında
Eğer yalnızca tam bağlı katmanlardan oluşan bir model (örneğin, bir derin perceptron) kullanıyorsanız, düzleştirme işlemini modelin giriş aşamasında yapmanız gerekir.

Örnek:

python
Kodu kopyala
class MLPModel(nn.Module):
    def __init__(self):
        super(MLPModel, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)  # Düzleştirme
        x = self.fc1(x)
        x = self.fc2(x)
        return x
4. Transfer Learning ve Önceden Eğitilmiş Modellerde
Transfer öğrenme için önceden eğitilmiş bir CNN modeli kullanıyorsanız, genelde son convolutional katmanın çıktısını düzleştirmeniz gerekebilir.

Örnek:

python
Kodu kopyala
import torchvision.models as models

# Önceden eğitilmiş model
model = models.resnet18(pretrained=True)

# Özellik çıkarımı için
x = torch.randn(1, 3, 224, 224)
features = model(x)

# Düzleştirme işlemi (gerekliyse)
features = features.view(features.size(0), -1)
5. Özellikleri Manuel Olarak Düzleştirmeniz Gerekmediğinde
Düzleştirme yapmanıza gerek olmayan durumlar:

Eğer CNN veya RNN katmanlarını birbiri ardına kullanıyorsanız.
Veriniz doğrudan tam bağlı katmana uygun formatta zaten bir vektörse (örneğin, 1D tensörler).
Özet:
Düzleştirme işlemini kullanmanız gereken durumlar:

CNN sonrası tam bağlı katmanlara geçiyorsanız.
Giriş veriniz çok boyutluysa ancak modeliniz 1D tensör bekliyorsa.
Önceden eğitilmiş modellerde convolutional çıktıdan tam bağlı katmana geçiş yapıyorsanız.
Düzleştirme ihtiyacı, kullandığınız modelin mimarisine ve işlediğiniz verinin formatına bağlıdır. CNN kullanıyorsanız, düzleştirme genelde yalnızca tam bağlı katman öncesinde yapılır.

In [25]:
# DataLoader'dan veri almak
dataiter = iter(trainloader)
images, labels = next(dataiter)

# Tensörlerin boyutlarını kontrol edin
print(images.shape)  # Çıktı: torch.Size([64, 1, 28, 28])


torch.Size([64, 1, 28, 28])


In [26]:
# Görselleri yeniden şekillendirme
images = images.view(64, 1, 784)  # (batch_size, channels, flattened_size)
print(images.shape)  # Çıktı: torch.Size([64, 1, 784])


torch.Size([64, 1, 784])


In [29]:
import matplotlib.pyplot as plt
import numpy as np

def view_classify(img, ps):
    """Görüntüyü ve sınıflandırma sonuçlarını görselleştirir."""
    ps = ps.data.numpy().squeeze()
    fig, (ax1, ax2) = plt.subplots(figsize=(6,9), nrows=2)
    ax1.imshow(img.numpy().squeeze(), cmap='gray')
    ax1.axis('off')
    ax2.barh(np.arange(10), ps)
    ax2.set_aspect(0.1)
    ax2.set_yticks(np.arange(10))
    ax2.set_yticklabels(np.arange(10))
    ax2.set_title('Sınıflandırma Olasılıkları')
    ax2.set_xlim(0, 1.1)
    plt.tight_layout()


In [ ]:
img_idx=0
ps=model.forward(images[img_idx,:])
img=images[img_idx]
view_classify(img.view(1,28,28),ps)

In [ ]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

# Basit Model Tanımı
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(784, 10)  # 784 giriş, 10 sınıf çıkışı

    def forward(self, x):
        return self.fc(x)

# Görselleştirme Fonksiyonu
def view_classify(img, ps):
    ps = ps.detach().numpy().squeeze()  # Olasılıkları numpy'a dönüştür
    fig, (ax1, ax2) = plt.subplots(figsize=(6, 9), nrows=2)

    # Görüntüyü göster
    ax1.imshow(img.numpy().squeeze(), cmap='gray')
    ax1.axis('off')

    # Sınıflandırma olasılıklarını görselleştir
    ax2.barh(np.arange(10), ps)
    ax2.set_aspect(0.1)
    ax2.set_yticks(np.arange(10))
    ax2.set_yticklabels(np.arange(10))
    ax2.set_title('Sınıflandırma Olasılıkları')
    ax2.set_xlim(0, 1.1)
    plt.tight_layout()
    plt.show()

# Modeli oluşturma
model = SimpleModel()

# Daha küçük veri (2 örnek, 784 özellik)
images = torch.randn(2, 784)  # 2 örnek, her biri 28x28 boyutunda düzleştirilmiş

# Belirli bir örneği seçmek
img_idx = 0
single_image = images[img_idx, :].unsqueeze(0)  # Batch boyutu eklemek için unsqueeze kullanıyoruz

# Modeli çalıştır ve olasılıkları al
logits = model(single_image)  # Modelin çıkışı
ps = nn.functional.softmax(logits, dim=1)  # Olasılık hesaplama

# Görüntüyü orijinal boyutuna döndür (28x28)
img = images[img_idx, :].view(1, 28, 28)

# Görselleştirme
view_classify(img, ps)


In [2]:
import torch.nn.functional as F

In [3]:
from torch import nn

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# MNIST veri setini yükleme ve veriyi normalize etme
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

trainset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

# DataLoader ile veriyi batch'ler halinde alacak şekilde ayarlama
trainloader = DataLoader(trainset, batch_size=64, shuffle=True)

# MLP Modeli tanımlama
class MLPModel(nn.Module):
    def __init__(self):
        super(MLPModel, self).__init__()
        self.fc1 = nn.Linear(784, 128)  # İlk katman: 784 giriş (28x28), 128 çıkış
        self.fc2 = nn.Linear(128, 64)   # İkinci katman: 128 giriş, 64 çıkış
        self.fc3 = nn.Linear(64, 10)    # Üçüncü katman: 64 giriş, 10 çıkış (sınıf sayısı)

    def forward(self, x):
        x = self.fc1(x)  # İlk katmanla ileri geçiş
        x = F.relu(x)    # ReLU aktivasyon fonksiyonu
        x = self.fc2(x)  # İkinci katmanla ileri geçiş
        x = F.relu(x)    # ReLU aktivasyon fonksiyonu
        x = self.fc3(x)  # Üçüncü katmanla ileri geçiş
        x = F.softmax(x, dim=1)  # Softmax ile sınıf olasılıkları
        return x

# Modeli oluşturma
model = MLPModel()

# Bir batch veri almak (DataLoader'dan)
dataiter = iter(trainloader)  # DataLoader'dan bir iterator oluştur
images, labels = next(dataiter)  # Bir batch al

# Seçilen bir görseli al (img_idx 0, yani ilk görüntü)
img_idx = 0
ps = model(images[img_idx].view(1, -1))  # Görseli düzleştirip modele veriyoruz
img = images[img_idx]  # Seçilen görseli kaydet

# Tahmin ve görselleştirme fonksiyonu
def view_classify(img, ps):
    '''Görseli ve tahmini gösterir'''
    ps = ps.detach().numpy().squeeze()  # Olasılıkları numpy formatına dönüştür ve squeeze ile düzleştir
    fig, (ax1, ax2) = plt.subplots(figsize=(6,3), ncols=2)  # 2 kolonlu bir grafik oluştur
    ax1.imshow(img.squeeze(), cmap='gray')  # Görseli gri tonlamada göster
    ax1.set_title(f'Tahmin: {ps.argmax()} (probability: {ps.max():.3f})')  # Tahmin edilen sınıf ve olasılığı
    ax1.axis('off')  # Görselleştirme sırasında eksenleri kapat

    ax2.barh(range(10), ps)  # Olasılıkları yatay çubuk grafik ile göster
    ax2.set_yticks(range(10))  # Y eksenindeki etiketler
    ax2.set_yticklabels([str(i) for i in range(10)])  # 0-9 arasında etiketler
    ax2.set_title('Sınıf Olasılıkları')  # Başlık
    plt.show()  # Görseli göster

# Görselleştirmeyi çağırma
view_classify(img, ps)


KeyboardInterrupt: 

In [4]:
from collections import OrderedDict
import torch.nn as nn

# Giriş, gizli katman boyutları ve çıkış boyutları
input_size = 784  # Örneğin, MNIST için 28x28 = 784
hidden_sizes = [128, 64]  # Örnek gizli katman boyutları
output_size = 10  # 10 sınıf (MNIST gibi)

model = nn.Sequential(OrderedDict([
    ("fcl1", nn.Linear(input_size, hidden_sizes[0])),  # İlk tam bağlantılı katman
    ("relu1", nn.ReLU()),  # İlk ReLU aktivasyonu
    ("fcl2", nn.Linear(hidden_sizes[0], hidden_sizes[1])),  # İkinci tam bağlantılı katman
    ("relu2", nn.ReLU()),  # İkinci ReLU aktivasyonu
    ("output", nn.Linear(hidden_sizes[1], output_size)),  # Çıkış katmanı
    ("softmax", nn.Softmax(dim=1))  # Softmax çıkış
]))

print(model)


AttributeError: module 'torch' has no attribute 'cuda'

In [ ]:


Kodun Açıklaması:
OrderedDict Kullanımı:

OrderedDict, Python'un standart dict sınıfına benzer, ancak eklediğiniz öğelerin sırasını korur. Burada, OrderedDict, modelin katmanlarını belirli bir sırayla tutmak için kullanılıyor.
nn.Sequential:

nn.Sequential, verilen katmanları sırayla birleştirir ve bunları otomatik olarak birbirine bağlar. Burada, modeldeki her katman bir önceki katmandan çıktı alacak şekilde sıralanır.
Katmanlar:

("fcl", nn.Linear(input_size, hidden_sizes[0])):

İlk katman, input_size giriş boyutuna sahip, ve hidden_sizes[0] kadar çıkış üretecek bir fully connected (tam bağlantılı) katmandır.
("relu1", nn.ReLU()):

İkinci katman, ReLU aktivasyon fonksiyonunu uygular. Bu, doğrusal olmayan bir aktivasyon fonksiyonudur ve genellikle sinir ağlarında kullanılır.
("fcl2", nn.Linear(input_size, hidden_sizes[0])):

Burada bir hata var. input_size'ı hidden_sizes[0]'a bağlayan ikinci bir fully connected katmanı tanımlıyorsunuz, ancak genellikle buradaki giriş boyutunun, önceki katmandan gelen çıkışa göre olması gerekir. Bu, bir hata olabilir.
("relu2", nn.ReLU()):

İkinci ReLU aktivasyonu, ikinci fully connected katmandan gelen çıktıya uygulanır.
("output", nn.Linear(output_sizes[1], output_size)):

Çıktı katmanı, output_sizes[1] giriş boyutuna sahip ve output_size kadar çıktı veren bir fully connected katmandır.
("softmax", nn.Softmax(dim=1)):

Softmax fonksiyonu, her sınıf için olasılık değerlerini hesaplar ve toplamının 1 olmasını sağlar. dim=1 parametresi, her örnek için (batch içindeki her satır) softmax işlemi yapılacağını belirtir.